project_name: easy_api_prom_sms_alert
before:
  hooks:
  - go mod tidy
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"
      - "^chore:"
      - "^Merge"
release:
  prerelease: auto
builds:
  - id: easy_api_prom_sms_alert
    dir: cmd
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64